config/routes.rb
Rails.application.routes.draw do
  # get 'profiles/show'
  # get 'profile/index'

  devise_for :users

  #get 'mailing/index'

  root to: 'mailings#index'

  resource :profile, only: [:show, :edit, :update], path_names: { :show => '' }

  resource :dashboard, only: [:show, :new, :create, :edit, :update], path_names: { :show => '' }

  resource :postal_code, only: [:create] #, path_names: { :create => '' }
  resources :mailings

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)

      #   if user.superadmin_role? || user.admin_role?
      #       can :manage, :all
      #       can :access, :rails_admin       # only allow admin users to access Rails Admin
      #       can :manage, :dashboard         # allow access to dashboard
      #   end

      #   if user.employee_role?
      #       can :manage, User
      #   end
    can :read, :all                 # allow everyone to read everything
    return unless user && user.admin?
    can :access, :rails_admin       # only allow admin users to access Rails Admin
    can :read, :dashboard           # allow access to dashboard
    if user.role? :superadmin
      can :manage, :all             # allow superadmins to do anything
    elsif user.role? :manager
      can :manage, [User, Product]  # allow managers to do anything to products and users
    elsif user.role? :sales
      can :update, Product, hidden: false  # allow sales to only update visible products
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mailing.rb
class Mailing < ApplicationRecord
  belongs_to :user
end

app/models/postal_code.rb
class PostalCode < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :mailings

  before_create :build_profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  load_and_authorize_resource
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show

  end

  def new

  end

  def create

  end

  def update

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!, :only => [:index]

  def index
  end
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create
    @mailing = Mailing.new#(mailing_params)
    @mailing.user_id = current_user.id

    @departure_point = '344000'
    @place_of_arrival = '347935'

    create_track

    @mailing.track_number = @new_track_number

    if @mailing.save
      redirect_to @mailing
    else
      render action: 'new'
      #render @mailing.errors.full_messages
    end
  end

  def create_track
    t = Time.now
    data = t.strftime("%d%m%Y")

    nof = current_user.id.to_s

    @new_track_number = 'RR' + data + nof + @departure_point + @place_of_arrival
  end

  # private

  # def mailing_params
  #   params.require(:mailing).permit(:track_number)
  # end

end

app/controllers/postal_codes_controller.rb
class PostalCodesController < ApplicationController
  def create
    @postcode = PostalCode.new(postal_code_params)

    if @postcode.save
      redirect_to dashboard_path
    else
      render 'dashboard/show'
    end
  end

  private
  def postal_code_params
    params.require(:postal_code).permit(:postcode, :city)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(current_user.id)
  end

  def edit
    @profile = Profile.find(current_user.id)
  end

  def update
    @profile = Profile.find(current_user.id)

    if @profile.update(profile_params)
      redirect_to profile_path
    else
      render action: 'edit'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :home_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/helpers/postal_codes_helper.rb
module PostalCodesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>
<br/>

<%= form_for :postal_code, url: postal_code_path do |f| %>

	<div class="field">
	    <%= f.label :postcode %><br />
	    <%= f.text_field :postcode, class: "form-control col-3" %>
 	</div>

 	<div class="field">
	   <%= f.label :city %><br />
	   <%= f.text_field :city, class: "form-control col-3" %>
 	</div>

	<br/><%= f.submit 'Create postcode', class: "btn btn-primary" %>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <title>Postal Service</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Postal Service', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'Create Mailing', new_mailing_path, class: "nav-item nav-link" %>    
        </div>
        <div class="ml-auto p-2 bd-highlight"> <!-- Размещение эл-та в крайнем правом углу-->
      
        <% if user_signed_in? %>

          <b class="username_style"><%= current_user.username %></b>

          <%= link_to 'Dashboard', dashboard_path, class: "btn btn-outline-success" %>

          <%= link_to 'Profile', profile_path, class: "btn btn-outline-primary" %>
          
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>

        <% else %>

          <%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-success" %>

        <% end %>

      </div>
      </nav>
        
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/mailings/index.html.erb
<h1>Postal Service</h1>
<br/>
<h3>Search or Track Packages</h3>

<%= form_for :mailing, url: mailings_path do |f| %>

	<div class="field">
	    <%= f.label :track_number %><br />
	    <%= f.text_field :track_number, class: "form-control col-3" %>
 	 </div>

	<br/><%= f.submit 'Find mailing', class: "btn btn-primary" %>

<% end %>

app/views/mailings/new.html.erb
<h1>New Mailing</h1>

<%= form_for :mailing, url: mailings_path do |f| %>


<p>
	<%= f.submit class: "btn btn-primary" %>
</p>
	<% end %>

app/views/profiles/show.html.erb
<div class="container">
    <div class="row m-y-2">
        <div class="col-lg-8 push-lg-4">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Messages</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#edit" data-toggle="tab" class="nav-link">Edit</a>
                </li>
            </ul>
            <div class="tab-content p-b-3">
                <div class="tab-pane active" id="profile">
                    <h4 class="m-y-2">User Profile</h4>
                    <div class="row">
                        <div class="col-md-12">
                            <p>Your login: <b><%= @profile.user.username %></b></p>

							<p>Your email address: <b><%= @profile.user.email %></b></p>

							<p>Your first name: <b><%= @profile.first_name %></b></p>

							<p>Your last name: <b><%= @profile.last_name %></b></p>

							<p>Your home address: <b><%= @profile.home_address %></b></p>

							<p><small  class="form-text text-muted">Registration date:  <%= @profile.user.created_at %></small>
</p>
                        </div>
                    </div>
                    <!--/row-->
                </div>
                <div class="tab-pane" id="messages">
                    <h4 class="m-y-2">Recent Messages &amp; Notifications</h4>
                    <div class="alert alert-info alert-dismissable">
                        <a class="panel-close close" data-dismiss="alert">×</a> This is an <strong>.alert</strong>. Use this to show important messages to the user. </div>
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <td>
                                    <span class="pull-xs-right font-weight-bold">3 hrs ago</span> Here is your a link to the latest summary report from the.. </td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="pull-xs-right font-weight-bold">Yesterday</span> There has been a request on your account since that was.. </td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="pull-xs-right font-weight-bold">9/10</span> Porttitor vitae ultrices quis, dapibus id dolor. Morbi venenatis lacinia rhoncus. </td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="pull-xs-right font-weight-bold">9/4</span> Vestibulum tincidunt ullamcorper eros eget luctus. </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane" id="edit">
                    <h4 class="m-y-2">Edit Profile</h4>

                    <!-- <form role="form"> -->
                    	<%= form_for :profile, url: profile_path(@profile), method: :put do |f| %>
                        <div class="form-group row">
                            <%= f.label :first_name, class: "col-lg-3 col-form-label form-control-label" %>
                            <div class="col-lg-9">
                            	<%= f.text_field :first_name, class: "form-control" %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <%= f.label :last_name, class: "col-lg-3 col-form-label form-control-label" %>
                            <div class="col-lg-9">
                            	<%= f.text_field :last_name, class: "form-control" %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <%= f.label :home_address, class: "col-lg-3 col-form-label form-control-label" %>
                            <div class="col-lg-9">
                            	<%= f.text_field :home_address, class: "form-control" %>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <div class="col-lg-9">
                                <%= f.submit "Cancel", class: "btn btn-secondary" %>
                                <%= link_to 'Edit User', edit_user_registration_path, class: "btn btn-success" %>
                                <%= f.submit "Save Changes", class: "btn btn-primary" %>
                            </div>
                        </div>

                    <!-- </form> -->
                    <% end %>
                </div>
            </div>
        </div>

        <div class="col-lg-4 pull-lg-8 text-xs-center">
            <img src="//placehold.it/150" class="m-x-auto img-fluid img-circle" alt="avatar">
            <h6 class="m-t-2">Upload a different photo</h6>
            <div class="custom-file">
			  <input type="file" class="custom-file-input" id="customFile">
			  <label class="custom-file-label" for="customFile">Choose file</label>
			</div>

        </div>

    </div>
</div>
<hr>